<?php
  /*
  Copyright 2004  Modulus Video, Inc.

  This file should be included in every document on the site, in the <head>
  section by including the following line:

      <?php require("${phpdir}/template/head.inc"); ?>

  This script places the typical page header information in every page.
  */
?>
<meta name="description" content="Modulus Video, Modulus Video is focused on providing H.264/MPEG-4 AVC products for high definition television. MPEG-2 video fueled explosive growth of digital television in the 1990's. Modulus Video believes H.264/MPEG-4 AVC is the key to unleash the potential of HDTV." />
<meta name="keywords" content="Modulus Video, video, H.264/MPEG-4 AVC, high definition television, MPEG-2, digital television, HDTV" />
<meta name="copyright" content="Copyright (c) 2004 Modulus Video, Inc.  All Rights Reserved." />
<meta name="rating" content="General" />
<meta name="revisit-after" content="30 Seconds" />
<meta name="doc-class" content="Living Document" />
<link rel="home" href="/" />
<link rel="shortcut icon" type="image/ico" href="/favicon.ico" />
<style type="text/css" media="all">@import "/css/devqamenu.css";</style>
<style type="text/css" media="print">@import "/css/devwebprint.css";</style>
