<div id="menubox" class="boxouter">
<div class="boxtop"><h2>Debug</h2></div>
<div class="boxbody">
<h4>Debug Views</h4>
<a id="debug_index" href="/mvdebug/" title="Debug Welcome Information">Welcome</a>
<a id="debug_unsupported" href="/mvdebug/unsupported.php" title="Edit Unsupported Configuration Variables">Unsupported Features</a>
<a id="debug_config" href="/mvdebug/config.php" title="Debug All Configuration Variables">Configuration</a>
<a id="debug_log" href="/mvdebug/log.php" title="Show the Contents of the Current Log">Current Log</a>
<a id="debug_oldlog" href="/mvdebug/oldlog.php" title="Show the Contents of the Old Log (before last reboot)">Old Log</a>
<a id="debug_dmesg" href="/mvdebug/dmesg.php" title="Show the Output from dmesg">Dmesg Output</a>
<a href="/" title="Return to the non-debug pages">Return to Standard View</a>
</div>  <!-- div.boxbody -->
</div>  <!-- div#menubox -->
