<div class="submenubox right200">
<h4>All Install Pages</h4>
<a id="install_index" href="install.php">Check Which Packages are Currently Installed</a>
<a id="install_support" href="install-support.php">How to Install Support Packages</a>
<a id="install_product" href="install-product.php">How to Install Product Packages</a>
<a id="install_supdown" href="support-downloads.php">Download Support Packages</a>
</div>
