<div id="menubox" class="boxouter">
<div class="boxtop"><h2>MV QA Main Menu</h2></div>
<div class="boxbody">
<h4>Information</h4>
<a id="main_index" href="/" title="Welcome to Modulus Video QA Web Server">Welcome</a>
<a id="tests_plans" href="/tests_plans.php" title="Current Test Plans">Test Plans</a>
<a id="tests_tools" href="/tests_tools.php" title="Tests Tools">Test Tools</a>
<a id="test_bed" href="/test_bed.php" title="Test Bed">Test Bed</a>
<a id="web_info" href="/info.php" title="Info">Info</a>
<a id="test_search" href="/mvsearch_run.php" title="MVSearch">MV Search Engine</a>
<a id="test_log" href="/mvlogrecv.php" title="MVLogRecv">MV Log Receive</a>
<h4>QA Monitor</h4>
<a id="hd_monitor" href="/hdmon.php" title="HD">HD Monitor</a>
<a id="sd_monitor" href="/sdmon.php" title="SD">SD Monitor</a>
<a id="z_monitor" href="/zmon.php" title="Zodiac">Zodiac Monitor</a>
<a id="p_monitor" href="/pmon.php" title="Polaris">Polaris Monitor</a>
<a id="s_monitor" href="/statmuxmon.php" title="StatMux">StatMux Monitor</a>
<a id="r_monitor" href="/rockstarmon.php" title="Rockstar">Rockstar Monitor</a>
<h4>Test Reports</h4>
<a id="tests_reports" href="/tests_reports.php" title="Reports">View Reports</a>
<a id="enter_tests_reports" href="/enter_report.php" title="Enter Reports">Enter Reports</a>
<h4>Compatibility Matrices</h4>
<a id="product_matrix" href="/products.php" title="By Products">Products</a>
<a id="release_matrix" href="/releases.php" title="By Releases">Releases</a>
</div>  <!-- div.boxbody -->
</div>  <!-- div#menubox -->
